vich_uploader:
    db_driver: orm

    mappings:
        products:
           uri_prefix: /images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
        header:
           uri_prefix: /images/header
           upload_destination: '%kernel.project_dir%/public/images/header'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
